version: "3"

services:

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 1025:1025 # SMTP
      - 8025:8025 # HTTP
    networks:
      - public

  alert-manager:
    volumes:
      - ${PWD}/mailhog-server/alertmanager.yml:/alertmanager.yml
    command:
      - '--config.file=/alertmanager.yml'

